version: "3.7"

services:
  server:
    build: .
    volumes:
      - ./path/to/appsettings.json:/Navislamia/appsettings.json
    environment:
      - Database__DataSource=db
    networks:
      - navislamia
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "N@vislam1a"
    networks:
      - navislamia
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@navislamia.com"
      PGADMIN_DEFAULT_PASSWORD: "N@vislam1a"

networks:
  navislamia:
    external: false